from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from typing import Optional
import json

from agents.graph import lesson_graph, strategy_graph, assessment_graph
from database import supabase

router = APIRouter()

class LessonPlanRequest(BaseModel):
    level: str; grade: str; area: str; topic: str; duration: str; context: Optional[str] = None
    current_draft: Optional[str] = None
    refinement_prompt: Optional[str] = None

class StrategyRequest(BaseModel):
    level: str; grade: str; area: str; topic: str; challenge: Optional[str] = None
    current_draft: Optional[str] = None
    refinement_prompt: Optional[str] = None

class AssessmentRequest(BaseModel):
    level: str; grade: str; area: str; topic: str; type: str; outcomes: Optional[str] = None
    current_draft: Optional[str] = None
    refinement_prompt: Optional[str] = None

class SaveDocumentRequest(BaseModel):
    title: str
    type: str
    content: str
    metadata: dict
    user_id: Optional[str] = None

async def stream_agent(graph, state_payload: dict):
    initial_state = {"revision_count": 0, "is_approved": False, "review_feedback": [], **state_payload}
    
    async def event_generator():
        try:
            # astream_events (v2) lets us listen to every step of the LangGraph workflow
            async for event in graph.astream_events(initial_state, version="v2"):
                kind = event["event"]
                
                # 1. Announce which node is currently running
                if kind == "on_node_start":
                    node_name = event["name"]
                    if node_name == "draft_node":
                        # Tell the frontend to clear the text (in case this is a revision loop)
                        yield f"data: {json.dumps({'type': 'clear'})}\n\n"
                        yield f"data: {json.dumps({'type': 'status', 'content': 'Drafting content...'})}\n\n"
                    elif node_name == "review_node":
                        yield f"data: {json.dumps({'type': 'status', 'content': 'Evaluating against KICD standards...'})}\n\n"
                
                # 2. Stream the actual words as they are generated by Gemini
                elif kind == "on_chat_model_stream":
                    # We only want to stream the text from the drafting phase, not the reviewer's internal JSON
                    if event["metadata"].get("langgraph_node") == "draft_node":
                        chunk = event["data"]["chunk"].content
                        if chunk:
                            yield f"data: {json.dumps({'type': 'token', 'content': chunk})}\n\n"
                            
        except Exception as e:
            yield f"data: {json.dumps({'type': 'error', 'content': str(e)})}\n\n"

    return StreamingResponse(event_generator(), media_type="text/event-stream")

@router.post("/db/save")
async def save_document(req: SaveDocumentRequest):
    try:
        # Insert the data into the 'documents' table
        data, count = supabase.table('documents').insert({
            "title": req.title,
            "type": req.type,
            "content": req.content,
            "metadata": req.metadata,
            "user_id": req.user_id
        }).execute()
        
        return {"status": "success", "message": "Document saved!", "data": data[1]}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to save document: {str(e)}")

@router.post("/generate/lesson-plan")
async def generate_lesson(req: LessonPlanRequest):
    return await stream_agent(lesson_graph, req.dict())

@router.post("/generate/teaching-strategies")
async def generate_strategies(req: StrategyRequest):
    return await stream_agent(strategy_graph, req.dict())

@router.post("/generate/assessment")
async def generate_assessment(req: AssessmentRequest):
    payload = req.dict()
    payload["assessment_type"] = payload.pop("type")
    return await stream_agent(assessment_graph, payload)